### ISSUE TITLE
NotImplementedError: Can't find 0x989 hw_code in config

### ISSUE THREAD

**Issue by Yatorime** [MTK-bypass/bypass_utility#100]
I have Samsung Galaxy A22 5G SM-A226B with mt-6833
Story short. my friend formated 
emmc Start_addr: 0x1E000000
Format Length: 0x80000

and phone now is dead. 
My laptop recognize it but restarts to different mode usb com port and Mediatek Vcom modes.
SP Flashtool can flash few things but i got error about verfied boot.
So i tried mtk client and bupass tool and got this as outout..
I wish i could revive the phone.
Symptoms: no screen, no charge, no charging lights, no sound.

So i followed a guide and end result is pretty bad. here is log..

C:\bypass_utility-v.1.4.2>python main.py
[2023-01-26 17:28:18.119721] Waiting for device
[2023-01-26 17:28:24.192838] Found port = COM3
Traceback (most recent call last):
  File "C:\bypass_utility-v.1.4.2\main.py", line 213, in <module>
    main()
  File "C:\bypass_utility-v.1.4.2\main.py", line 44, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\bypass_utility-v.1.4.2\main.py", line 153, in get_device_info
    raise e
  File "C:\bypass_utility-v.1.4.2\main.py", line 146, in get_device_info
    config = Config().default(hw_code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\bypass_utility-v.1.4.2\src\config.py", line 15, in default
    self.from_file(config, hw_code)
  File "C:\bypass_utility-v.1.4.2\src\config.py", line 28, in from_file
    raise NotImplementedError("Can't find {} hw_code in config".format(hw_code))
NotImplementedError: Can't find 0x989 hw_code in config

C:\bypass_utility-v.1.4.2>

**Comment by sherlongqu** [comment]
[This maybe give you help](https://github.com/MTK-bypass/bypass_utility/issues/22)
