### ISSUE TITLE
Value error MT6785

### ISSUE THREAD

**Issue by karimnagdii** [MTK-bypass/bypass_utility#101]
`[2023-01-29 07:09:56.173679] Waiting for device
[2023-01-29 07:10:16.861122] Found port = COM10
Traceback (most recent call last):
  File "C:\Users\user\Desktop\bypass_utility-v.1.4.2\main.py", line 213, in <module>
    main()
  File "C:\Users\user\Desktop\bypass_utility-v.1.4.2\main.py", line 44, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\bypass_utility-v.1.4.2\main.py", line 146, in get_device_info
    config = Config().default(hw_code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\bypass_utility-v.1.4.2\src\config.py", line 15, in default
    self.from_file(config, hw_code)
  File "C:\Users\user\Desktop\bypass_utility-v.1.4.2\src\config.py", line 23, in from_file
    config = json5.load(config)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\json5\lib.py", line 45, in load
    return loads(s, encoding=encoding, cls=cls, object_hook=object_hook,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\json5\lib.py", line 81, in loads
    raise ValueError(err)
ValueError: <string>:8 Unexpected "<" at column 1`

what to do

**Comment by kngharv** [comment]
strange,  I ran into this issue using Linux as well.  I am also using version 1.4.2 and Python 3.10
