### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by laerte1000** [MTK-bypass/bypass_utility#104]
I have tried redownloading, rebooting, but nothing works, this is the error i get: 
`[2023-06-09 15:54:08.191908] Waiting for device
[2023-06-09 15:54:08.191908] Found device = 0e8d:20ff
Traceback (most recent call last):
  File "C:\Users\Lucec\OneDrive\Desktop\bypass_utility-master\main.py", line 237, in <module>
    main()
  File "C:\Users\Lucec\OneDrive\Desktop\bypass_utility-master\main.py", line 40, in main
    device = Device().find()
  File "C:\Users\Lucec\OneDrive\Desktop\bypass_utility-master\src\device.py", line 109, in find
    self.ep_in = usb.util.find_descriptor(cdc_if, custom_match=lambda x: usb.util.endpoint_direction(x.bEndpointAddress) == usb.util.ENDPOINT_IN)
  File "C:\Users\Lucec\AppData\Roaming\Python\Python310\site-packages\usb\util.py", line 192, in find_descriptor
    return _interop._next(desc_iter(**args))
  File "C:\Users\Lucec\AppData\Roaming\Python\Python310\site-packages\usb\_interop.py", line 68, in _next
    return next(iter)
  File "C:\Users\Lucec\AppData\Roaming\Python\Python310\site-packages\usb\util.py", line 183, in desc_iter
    for d in desc:
TypeError: 'NoneType' object is not iterable`

**Comment by laerte1000** [comment]
Can anybody help?

**Comment by nate1604** [comment]
I am getting this identical error. I ran the program from the FireISO image of linux.
