### ISSUE TITLE
Can't find 0x1066 hw_code in config

### ISSUE THREAD

**Issue by riadfattal** [MTK-bypass/bypass_utility#108]
I accidentally bricked my infinix note 11s and I need this tool to bypass bootrom
I followed instructions on how to install carefully and when I try it it shows this reply
C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2>python main.py
[2023-07-24 15:52:29.547889] Waiting for device
[2023-07-24 15:52:30.580886] Found port = COM15
Traceback (most recent call last):
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 213, in <module>
    main()
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 44, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 153, in get_device_info
    raise e
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 146, in get_device_info
    config = Config().default(hw_code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\src\config.py", line 15, in default
    self.from_file(config, hw_code)
  File "C:\Users\sima\Desktop\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\src\config.py", line 28, in from_file
    raise NotImplementedError("Can't find {} hw_code in config".format(hw_code))
NotImplementedError: Can't find 0x1066 hw_code in config

**Comment by MHFAYCEL** [comment]
[2023-07-28 06:37:44.638871] Waiting for device
[2023-07-28 06:38:06.701415] Found port = COM3
[2023-07-28 06:38:07.018625] Can't find 0x1066 hw_code in config
[2023-07-28 06:38:07.018625] Device hw code: 0x1066
[2023-07-28 06:38:07.018625] Device hw sub code: 0x8a00
[2023-07-28 06:38:07.018625] Device hw version: 0xca00
[2023-07-28 06:38:07.018625] Device sw version: 0x0
[2023-07-28 06:38:07.018625] Device secure boot: True
[2023-07-28 06:38:07.018625] Device serial link authorization: False
[2023-07-28 06:38:07.018625] Device download agent authorization: True
[2023-07-28 06:38:07.018625] Found device in preloader mode, trying to crash...
[2023-07-28 06:38:07.034248] status is 7024
[2023-07-28 06:38:07.061528] Waiting for device
[2023-07-28 06:38:29.233485] Found port = COM3
[2023-07-28 06:38:29.490129] Can't find 0x1066 hw_code in config
[2023-07-28 06:38:29.505753] Device hw code: 0x1066
[2023-07-28 06:38:29.505753] Device hw sub code: 0x8a00
[2023-07-28 06:38:29.505753] Device hw version: 0xca00
[2023-07-28 06:38:29.505753] Device sw version: 0x0
[2023-07-28 06:38:29.505753] Device secure boot: True
[2023-07-28 06:38:29.505753] Device serial link authorization: False
[2023-07-28 06:38:29.505753] Device download agent authorization: True
[2023-07-28 06:38:29.505753] Found device in preloader mode, trying to crash...
[2023-07-28 06:38:29.505753] status is 7024
[2023-07-28 06:38:29.561497] Waiting for device
