### ISSUE TITLE
Can't get my phone accept a handshake on mtkclient. using this program returns the following.

### ISSUE THREAD

**Issue by DeeKatsanos** [MTK-bypass/bypass_utility#112]
[2024-01-09 20:08:02.823314] Waiting for device
[2024-01-09 20:08:05.580099] Found device = 0e8d:0003
Traceback (most recent call last):
  File "C:\Users\mrHAC\Downloads\mtkclient\bypass_utility-master\main.py", line 237, in <module>
    main()
  File "C:\Users\mrHAC\Downloads\mtkclient\bypass_utility-master\main.py", line 42, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrHAC\Downloads\mtkclient\bypass_utility-master\main.py", line 158, in get_device_info
    device.handshake()
  File "C:\Users\mrHAC\Downloads\mtkclient\bypass_utility-master\src\device.py", line 167, in handshake
    self.write(sequence[i])
  File "C:\Users\mrHAC\Downloads\mtkclient\bypass_utility-master\src\device.py", line 226, in write
    self.ep_out.write(data[offset:][:self.ep_out.wMaxPacketSize if len(data) - offset > self.ep_out.wMaxPacketSize else len(data) - offset], self.timeout * 1000)
  File "C:\Users\mrHAC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 408, in write
    return self.device.write(self, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrHAC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\core.py", line 989, in write
    return fn(
           ^^^
  File "C:\Users\mrHAC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\backend\libusb1.py", line 837, in bulk_write
    return self.__write(self.lib.libusb_bulk_transfer,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrHAC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\backend\libusb1.py", line 938, in __write
    _check(retval)
  File "C:\Users\mrHAC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\usb\backend\libusb1.py", line 602, in _check
    raise USBTimeoutError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBTimeoutError: [Errno 10060] Operation timed out

----
device is sm-a145R, MT6769V. stuck in bootrom mode, removed the battery and "inserted" it again, no luck. no button combination seems to restart the phone.
----
edit2: managed to restart it and make my computer read it in bootrom mode, can't find a way to exit it though. mtk reset does nothing. also, log get's stuck to "Jumping to 0x200000: ok before unfreezing the gui

**Comment by sjanaX01** [comment]
Can You fix you phone

**Comment by DeeKatsanos** [comment]
> Can You fix you phone

Not really, gave up eventually, but if I pick it up again and make it I'll let you know how I did it. Is the project abandoned by the way?

**Comment by D3vShoaib** [comment]
i think its because your phone cant enter brom mode, there are 2 solutions for this 
1- open the device and disconnect  the battery (this will shutdown the phone)
2- wait for battery to drain (reverse charge, wait ..etc)

any how you need shutdown the phone and enter the brom mode correctly mostly by holding the [ vol +, - ] simultaneously and connecting the use while script is waiting

**Comment by DeeKatsanos** [comment]
Fixed my phone finally by booting to brom via testpoints, grabbing the expdb partition, opening it via a hex editor and debugging according to the boot logs (I replaced each partition that would cause the crash/shutdown and it finally got me to odin mode).
