### ISSUE TITLE
i can't run main.py on fedora

### ISSUE THREAD

**Issue by jusdMustafa** [MTK-bypass/bypass_utility#123]
i have this error when i run it i installed pyusb json5 and still get this error

mustafa@thinkpad-l590:~/bypass_utility$ ./main.py
Traceback (most recent call last):
  File "/home/mustafa/bypass_utility/./main.py", line 237, in <module>
    main()
  File "/home/mustafa/bypass_utility/./main.py", line 38, in main
    raise RuntimeError("Default config is missing")
RuntimeError: Default config is missing

**Comment by iijawadm** [comment]
did you know how to fix it or fedora isn't supported
