### ISSUE TITLE
Stuck at foundport, then it can't initiate a handshake

### ISSUE THREAD

**Issue by dlucigithub** [MTK-bypass/bypass_utility#128]
Phone is Redmi 13C 4G (mt6768)

[2024-11-10 18:31:29.266244] Waiting for device
[2024-11-10 18:31:35.204985] Found port = COM6
Traceback (most recent call last):
  File "C:\Users\ASUS\Downloads\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 213, in <module>
    main()
    ~~~~^^
  File "C:\Users\ASUS\Downloads\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 44, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\Downloads\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\main.py", line 134, in get_device_info
    device.handshake()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\ASUS\Downloads\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\src\device.py", line 92, in handshake
    self.write(0xA0)
    ~~~~~~~~~~^^^^^^
  File "C:\Users\ASUS\Downloads\bypass_utility-v.1.4.2\bypass_utility-v.1.4.2\src\device.py", line 144, in write
    self.dev.write(data)
    ~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\serial\serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')
serial.serialutil.SerialTimeoutException: Write timeout


**It gets stuck at found port, and when I disconnect it shows the rest?**

**Comment by AbubakarSiddique** [comment]
Have you got any solution? same issue here too.
