### ISSUE TITLE
Update main

### ISSUE THREAD

**Issue by mpotane** [MTK-bypass/bypass_utility#59]
2021-09-29 11:34:31.001508] Waiting for device
[2021-09-29 11:34:31.001979] Found device = 0e8d:201c
Traceback (most recent call last):
  File "main.py", line 237, in <module>
    main()
  File "main.py", line 40, in main
    device = Device().find()
  File "/home/p0txky/Documents/bypass_utility/src/device.py", line 109, in find
    self.ep_in = usb.util.find_descriptor(cdc_if, custom_match=lambda x: usb.util.endpoint_direction(x.bEndpointAddress) == usb.util.ENDPOINT_IN)
  File "/usr/local/lib/python3.8/site-packages/usb/util.py", line 192, in find_descriptor
    return _interop._next(desc_iter(**args))
  File "/usr/local/lib/python3.8/site-packages/usb/_interop.py", line 68, in _next
    return next(iter)
  File "/usr/local/lib/python3.8/site-packages/usb/util.py", line 183, in desc_iter
    for d in desc:
TypeError: 'NoneType' object is not iterable

**Comment by mpotane** [comment]
On Opensuse Tumbleweed
