### ISSUE TITLE
RuntimeError: Default config is missing

### ISSUE THREAD

**Issue by macdelft** [MTK-bypass/bypass_utility#73]
Hi, i receive error; RuntimeError: Default config is missing

The syntax i run;
C:\Users\MichielvanDelft\Downloads\bypass_utility-master\bypass_utility-master>python main.py
Traceback (most recent call last):
  File "C:\Users\MichielvanDelft\Downloads\bypass_utility-master\bypass_utility-master\main.py", line 237, in <module>
    main()
  File "C:\Users\MichielvanDelft\Downloads\bypass_utility-master\bypass_utility-master\main.py", line 38, in main
    raise RuntimeError("Default config is missing")
RuntimeError: Default config is missing

Is this a known issue, or am i doing something wrong? Many thanks in advance!

**Comment by macdelft** [comment]
I didn't RTFM :)

**Comment by EllsCafe** [comment]
Hey! How you solved the problem? I have the exact same error

**Comment by docfate111** [comment]
where in the manual does it say config? maybe an earlier branch?
