### ISSUE TITLE
Request bypass for dimensity8100(mt6895)

### ISSUE THREAD

**Issue by zeronao** [MTK-bypass/bypass_utility#86]
What't wrong with it?
[2022-08-02 02:12:20.913098] Found device = 0e8d:0003
Traceback (most recent call last):
  File "F:\d\Tool\spflash\bypass_utility-master\main.py", line 237, in <module>
    main()
  File "F:\d\Tool\spflash\bypass_utility-master\main.py", line 42, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
  File "F:\d\Tool\spflash\bypass_utility-master\main.py", line 177, in get_device_info
    raise e
  File "F:\d\Tool\spflash\bypass_utility-master\main.py", line 170, in get_device_info
    config = Config().default(hw_code)
  File "F:\d\Tool\spflash\bypass_utility-master\src\config.py", line 17, in default
    self.from_file(config, hw_code)
  File "F:\d\Tool\spflash\bypass_utility-master\src\config.py", line 30, in from_file
    raise NotImplementedError("Can't find {} hw_code in config".format(hw_code))
NotImplementedError: Can't find 0x1172 hw_code in config

**Comment by hoangzk9as** [comment]
I want it too

**Comment by Razer24** [comment]
I'd get rid of that as quickly as possible.

**Comment by sorasoras** [comment]
same here

**Comment by hoangzk9as** [comment]
Still hope

**Comment by Ekram7645** [comment]
Yes I am too😄
poco x4 gt dimensity 8100 Mt6895 

> 
![IMG_20221109_035734](https://user-images.githubusercontent.com/115436121/202292858-9fe9f4c0-bb2d-4e27-971b-83db19e6a88f.jpg)

Brom protocol error.check device environment!!!

**Comment by jhonny-oliveira** [comment]
waiting...

**Comment by suhanov6739** [comment]
вт, 20 дек. 2022 г., 12:30 Jhonny Oliveira ***@***.***>:

**Comment by Atassen21** [comment]
anyone got any solution?

**Comment by Atassen21** [comment]
im living with my brand new bricked phone [redmi k50i] 😥

**Comment by MSSX-Ifvo** [comment]
> 
bro im living with my bricked k50 too haha, it took me a whole day to turn it into a brick😂now im asking the vendor to take back the phone to repair ,but they asked me the imei of it ,i cant boot up my phone to check it and i lost my packing box😂such an annoying day😪

**Comment by Razer24** [comment]
guys with bricks write in telegram @Rafon24

**Comment by Razer24** [comment]
![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)

**Comment by quickbin** [comment]
> ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)

how to get it

**Comment by riabc23** [comment]
MT6895 Anyone found a solution for this? the device does not turn on ... auth bypass does not work ... please solution as soon as possible ...

**Comment by hulakk** [comment]
> ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)

how to get it

**Comment by ilkeroz17** [comment]
> > ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)
> 
> how to get it

how did you do this can you help me ? help

**Comment by tos430** [comment]
Please help me how to repair this Poco x4 GT anyone get a solved issue?

**Comment by whitehelper** [comment]
> Please help me how to repair this Poco x4 GT anyone get a solved issue?

Write to telegram @whitehelper3649

**Comment by Aezukla** [comment]
If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported

**Comment by betterdream2** [comment]
> If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported

I bricked my Oneplus cellphone with this SOC yesterday. But I don't have telegram. Do u have other way to contact u?

**Comment by whitehelper** [comment]
> > If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported
> 
> I bricked my Oneplus cellphone with this SOC yesterday. But I don't have telegram. Do u have other way to contact u?

yes, have

**Comment by betterdream2** [comment]
> > > If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported
> > 
> > 
> > I bricked my Oneplus cellphone with this SOC yesterday. But I don't have telegram. Do u have other way to contact u?
> 
> yes, have

Thanks, so what can I do?

**Comment by whitehelper** [comment]
> > > > If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported
> > > 
> > > 
> > > I bricked my Oneplus cellphone with this SOC yesterday. But I don't have telegram. Do u have other way to contact u?
> > 
> > 
> > yes, have
> 
> Thanks, so what can I do?

send your whatsapp

**Comment by kkinsky** [comment]
> ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)



> ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)

Hello Razer24, I need do this, can you Helô?
TY

**Comment by faheza** [comment]
> ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)

how did you do this can you help me ? my devices xiaomi 13T

**Comment by StaryPartisan** [comment]
> If anyone brick their phone (1+ or Xiaomi) write to Telegram @hxruofficial. D8100 supported

Thank you dear @hxruofficial for your help in restoring my phone! I recommend everyone to contact with him if your phone is bricked!

**Comment by gsmxda** [comment]
I have redmi k50i required MT6895 Bypass

**Comment by Quincy0309** [comment]
> Yes I am too😄 poco x4 gt dimensity 8100 Mt6895
> 
> > 
> 
> ![IMG_20221109_035734](https://user-images.githubusercontent.com/115436121/202292858-9fe9f4c0-bb2d-4e27-971b-83db19e6a88f.jpg)
> 
> Brom protocol error.check device environment!!

**Comment by Quincy0309** [comment]
i also got that error my device is redmi note 12t pro cn rom

**Comment by IronFox19** [comment]
hello, I also have a problem with the dimension 8100. does anyone have a solution to the problem

**Comment by IronFox19** [comment]
> hello, I also have a problem with the dimension 8100. does anyone have a solution to the problem . POCO X4 GT

**Comment by hooperq** [comment]
> > ![IMG_20230207_153835_534](https://user-images.githubusercontent.com/43329735/217241365-6feb01bd-d9ad-44f6-949a-0c96dcce06a4.jpg)
> 
> cómo conseguirlo

hola me puedes ayudar

**Comment by MansukhP23** [comment]
hy 
how can downgrade my device andorid 14 to 13 
Please Help Me!!!!!

**Comment by Aezukla** [comment]
> hy how can downgrade my device andorid 14 to 13 Please Help Me!!!!!

device?

**Comment by MansukhP23** [comment]
> > hy how can downgrade my device andorid 14 to 13 Please Help Me!!!!!
> 
> device?

Iqoo Neo 7

**Comment by MansukhP23** [comment]
I want downgrade my device iqoo Neo 7 Android 14 to 13

**Comment by saktoor** [comment]
same problem...

**Comment by mikelog** [comment]
I had the same issue, Xiaomi 12T
NotImplementedError: Can't find 0x1172 hw_code in config
