### ISSUE TITLE
Xiaomi Redmi note 8 pro (begonia) unbrick issue

### ISSUE THREAD

**Issue by elauqzz** [MTK-bypass/bypass_utility#89]
Whenever i run the bypass, one of those 2 things happen
1: does all the stuff then my PC BSODs out of the blue
2: whatever this is
[2022-08-25 20:57:38.662098] Waiting for bootrom
[2022-08-25 20:57:41.357839] Found port = COM4
Traceback (most recent call last):
  File "C:\Users\elauqzz\Downloads\Compressed\4.Bypass\main.py", line 65, in <module>
    main()
  File "C:\Users\elauqzz\Downloads\Compressed\4.Bypass\main.py", line 35, in main
    device.handshake()
  File "C:\Users\elauqzz\Downloads\Compressed\4.Bypass\src\device.py", line 88, in handshake
    self.check(self.read(1), to_bytes(0x5F))
  File "C:\Users\elauqzz\Downloads\Compressed\4.Bypass\src\device.py", line 84, in check
    raise RuntimeError("Unexpected output, expected {} got {}".format(gold, test))
RuntimeError: Unexpected output, expected 0x5f got 0xa0
Press any key to continue . . .

chipset is mt6785

EDIT: when i run sp flash tool after either of the outcomes, this appears (note: i was once doing this on a linux machine and some kind of  i/o error appeared, i then disconnected the phone, could that be the cause?)
![image](https://user-images.githubusercontent.com/103392006/186747709-84c123fd-0f08-4257-b8ea-2ac6b501e760.png)

EDIT 2: I'm running this command `py main.py -c mt6785_config.json5 -p mt6785_payload.bin` in a batch script, the full script content is @echo off
py main.py -c mt6785_config.json5 -p mt6785_payload.bin
pause
these are the contents of the folder :
![image](https://user-images.githubusercontent.com/103392006/186748801-c86e55f3-990c-4c9d-adcc-95ab7f1f0f41.png)

these are the logs 
[2022-08-25 20:44:24.661344] Waiting for bootrom
                                                                                 
[2022-08-25 20:44:28.687361] Found port = COM4

[2022-08-25 20:44:36.719692] Waiting for bootrom

[2022-08-25 20:44:39.955834] Found port = COM4

[2022-08-25 20:44:55.145572] Waiting for bootrom

[2022-08-25 20:44:58.639397] Found port = COM4

[2022-08-25 20:57:38.662098] Waiting for bootrom

[2022-08-25 20:57:41.357839] Found port = COM4

[2022-08-25 21:02:39.326038] Waiting for bootrom

[2022-08-25 21:02:42.784448] Found port = COM4
need help quickly since this is my main phone

**Comment by elauqzz** [comment]
FIXED! : KEEP YOUR PHONE PLUGGED IN AFTER THE BSOD AND INSTEAD OF SP FLASH TOOL USE MTKCLIENT
