### ISSUE TITLE
Can't find 0x1066 hw_code in config Error Showing Up

### ISSUE THREAD

**Issue by NiskoDT** [MTK-bypass/bypass_utility#99]
Did everything correctly, installed everything, rebooted pc, and still shows this error.

`[2023-01-21 18:27:59.684388] Waiting for device
[2023-01-21 18:28:02.558977] Found port = COM3
Traceback (most recent call last):
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\main.py", line 213, in <module>
    main()
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\main.py", line 44, in main
    config, serial_link_authorization, download_agent_authorization, hw_code  = get_device_info(device, arguments)
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\main.py", line 153, in get_device_info
    raise e
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\main.py", line 146, in get_device_info
    config = Config().default(hw_code)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\src\config.py", line 15, in default
    self.from_file(config, hw_code)
  File "C:\Users\eiffe\Downloads\Android Stuff\MTK Bypass\bypass_utility-v.1.4.2\src\config.py", line 28, in from_file
    raise NotImplementedError("Can't find {} hw_code in config".format(hw_code))
NotImplementedError: Can't find 0x1066 hw_code in config`

**Comment by riadfattal** [comment]
Did you fix this?

**Comment by NiskoDT** [comment]
> Did you fix this? 
No I stopped doing this. Was trying to root my device back then.
